### ISSUE TITLE
A Hitman mode

### ISSUE THREAD

**Issue by ManosSef** [yummypasta/MinecraftManhunt#54]
## Description
Manhunt is a game that requires time in order to be played from start to finish. But I don't always have enough time for a full manhunt with friends, so we need something less time-consuming. Adding a hitman mode would solve this problem for me and for others who potentially have this problem. The hitman mode is a manhunt where the world is around 750x750 blocks big, the runners are glowing and have to survive for a limited amount of time to win, just like Dream's Minecraft Survivalist VS 3 Hitmen video. I would love to see this feature in the plugin.

**Comment by yummypasta** [comment]
This issue is out of scope of the plugin, as it completely changes the core mechanics provided. It would probably be better to create a whole new plugin for this mode; or, if you want to retain some of the other features (such as Discord integration) feel free to create a fork of this repo and change some of the code!
